### ISSUE TITLE
Calendar doesn't show today's date

### ISSUE THREAD

**Issue by Sohail-XD** [qxb3/dotfiles#3]
![image](https://github.com/qxb3/gruvbox.hypr/assets/86248129/cdac28f1-7c21-4d84-9954-50170d1c8f6d)

**Comment by qxb3** [comment]
uhh yep, i haven't added that since i have no idea how xd

**Comment by Sohail-XD** [comment]
Damn. I'll try to figure that out but is there a way to make the music widget display items played in firefox?

**Comment by qxb3** [comment]
fixed on [#fa97da4](https://github.com/qxb3/conf/commit/fa97da445c0a1b98b87d8a0ec22c4e4e3ebd51cd).
