### ISSUE TITLE
change `tmp/hypr` to `$XDG_RUNTIME_DIR/hypr/` in eww scripts

### ISSUE THREAD

**Issue by pavel-hrdina** [qxb3/dotfiles#4]
Hyprland changed `tmp/hypr` to `$XDG_RUNTIME_DIR/hypr/`. This result in the eww scripts breaking. Mainly the `workspaces.sh` and `activewindow.sh`.

To fix this, the socat command needs to change to:

```bash
socat -u "UNIX-CONNECT:/$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
```

from: 

```bash
socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
```

**Comment by qxb3** [comment]
fixed on [9162032](https://github.com/qxb3/gruvbox.hypr/commit/9162032538f7ae24231315782b2c3b1e27fb89e0)
