### ISSUE TITLE
ags v2 breaks sidebar on yume

### ISSUE THREAD

**Issue by lewiwiii** [qxb3/dotfiles#7]
ags v2 released and killed some globals (more info [here](https://github.com/Aylur/ags/releases/tag/v2.0.0)), breaking the sidebar. 
In the meantime agsv1 can be used, [here's the PKGBUILD](https://github.com/kotontrion/PKGBUILDS/blob/main/agsv1/PKGBUILD) (note that the command changes from `ags` to `agsv1` so you'll have to edit hyprland.conf according to this change if you want to continue using v1)

**Comment by qxb3** [comment]
ah yep, I'm planning to migrate this and all configs that still uses v1 to use v2. For now, If you want you can use the yume-beyond (from the unofficial rice section) that is already migrated on v2, this config btw has some more features like colorscheme changer.

**Comment by lewiwiii** [comment]
thank you, i'll definitely check it out

**Comment by qxb3** [comment]
As of now, this repository will no longer focus solely on Gruvbox. Instead, it will explore various colorschemes.

Additionally, Yume, previously exclusive to Gruvbox, has been discontinued. The official Yume will now refer to what was previously known as Yume-Beyond.
